import type {
  Bootstrap,
  Customer,
  CustomerContactForm,
  CustomerForm,
  CountryConfig,
  CustomerLevel,
  CustomerStatus,
  CustomerType,
  FollowupForm,
  FollowupMethod,
  QuotationForm,
  UserForm,
  UserRole,
  UserStatus,
} from "./types";

export const roleOptions: { label: string; value: UserRole }[] = [
  { label: "顾问", value: "consultant" },
  { label: "管理员", value: "admin" },
  { label: "审批人", value: "approver" },
];
export const statusOptions: { label: string; value: UserStatus }[] = [
  { label: "启用", value: "active" },
  { label: "禁用", value: "inactive" },
];
export const followupMethodOptions: FollowupMethod[] = ["邮件", "电话", "微信", "会议", "其他"];
export const customerTypeOptions: CustomerType[] = ["企业", "个人", "律所", "代理机构", "其他"];
export const customerLevelOptions: CustomerLevel[] = ["普通", "重点", "战略", "暂停"];
export const customerStatusOptions: { label: string; value: CustomerStatus }[] = [
  { label: "启用", value: "active" },
  { label: "停用", value: "inactive" },
];
export const initialUserForm: UserForm = {
  name: "",
  email: "",
  password: "",
  role: "consultant",
  status: "active",
};
export const initialFollowupForm: FollowupForm = {
  method: "邮件",
  content: "",
  next_followup_date: "",
};
export const initialCustomerForm: CustomerForm = {
  name: "",
  customer_type: "企业",
  consultant_email: "suri@example.com",
  department: "",
  default_currency: "CNY",
  default_quote_terms: "",
  customer_level: "普通",
  status: "active",
  remark: "",
};
export const initialCustomerContactForm: CustomerContactForm = {
  name: "",
  title: "",
  email: "",
  phone: "",
  wechat: "",
  is_primary: true,
  remark: "",
};
export const fallbackCustomers: Customer[] = [
  {
    id: "cust-demo-zyip",
    customer_no: "C20260606-ZYIP-DEMO",
    name: "智造未来科技有限公司",
    customer_type: "企业",
    consultant_id: "u-consultant",
    consultant_email: "suri@example.com",
    consultant_name: "Suri",
    department: "知识产权部",
    default_currency: "USD",
    default_quote_terms: "报价有效期 30 天；官方费用、外所费用或汇率发生变化时，以最新确认为准。",
    customer_level: "重点",
    status: "active",
    remark: "初始化演示客户",
    created_at: "2026-06-06T00:00:00Z",
    updated_at: "2026-06-06T00:00:00Z",
    contacts: [
      {
        id: "cust-demo-zyip-contact-001",
        customer_id: "cust-demo-zyip",
        name: "Lina",
        title: "IP Manager",
        email: "lina@example.com",
        phone: "",
        wechat: "",
        is_primary: true,
        remark: "默认联系人",
        created_at: "2026-06-06T00:00:00Z",
        updated_at: "2026-06-06T00:00:00Z",
      },
    ],
  },
];

export const fallbackBootstrap: Bootstrap = {
  users: [
    { id: "u-consultant", name: "Suri", email: "suri@example.com", role: "consultant", status: "active" },
    { id: "u-admin", name: "管理员", email: "admin@example.com", role: "admin", status: "active" },
  ],
  countries: [
    { code: "US", name_cn: "美国", name_en: "United States", default_currency: "USD", enabled: true, jurisdiction_id: "jur-US", internal_code: "US", display_code: "US", jurisdiction_type: "single_country", is_enabled: true, iso_alpha2: "US", iso_alpha3: "USA", iso_numeric: "840", un_m49_code: "840", wipo_st3_code: "US", source_name: "legacy_countries", source_version: "phase_1_jurisdiction_compat", manual_override: true },
    { code: "EP", name_cn: "欧洲专利局", name_en: "European Patent Office", default_currency: "EUR", enabled: true, jurisdiction_id: "jur-EP", internal_code: "EP", display_code: "EPO", jurisdiction_type: "regional_office", is_enabled: true, wipo_st3_code: "EP", source_name: "WIPO ST.3", source_version: "WIPO ST.3 December 2025", manual_override: true },
    { code: "JP", name_cn: "日本", name_en: "Japan", default_currency: "JPY", enabled: true, jurisdiction_id: "jur-JP", internal_code: "JP", display_code: "JP", jurisdiction_type: "single_country", is_enabled: true, iso_alpha2: "JP", iso_alpha3: "JPN", iso_numeric: "392", un_m49_code: "392", wipo_st3_code: "JP", source_name: "legacy_countries", source_version: "phase_1_jurisdiction_compat", manual_override: true },
    { code: "KR", name_cn: "韩国", name_en: "Korea", default_currency: "KRW", enabled: true, jurisdiction_id: "jur-KR", internal_code: "KR", display_code: "KR", jurisdiction_type: "single_country", is_enabled: true, iso_alpha2: "KR", iso_alpha3: "KOR", iso_numeric: "410", un_m49_code: "410", wipo_st3_code: "KR", source_name: "legacy_countries", source_version: "phase_1_jurisdiction_compat", manual_override: true },
  ],
  application_types: ["发明", "实用新型", "外观"],
  filing_routes: ["直接申请", "巴黎公约", "PCT进入"],
  currencies: ["CNY", "USD", "EUR", "JPY", "KRW"],
  statuses: ["草稿", "已生成报价", "已发送客户", "待跟进", "跟进中", "跟进逾期", "需价格调整", "已确认", "部分开卷", "已开卷", "框架协议", "未成交", "已作废"],
  fee_rules: [],
  translation_rules: [],
};

export const emptyCountryConfig: CountryConfig = {
  countries: [],
  treaty_rules: [],
  path_rules: [],
  deadline_rules: [],
  entity_type_rules: [],
  language_rules: [],
  fx_tax_rules: [],
  special_rules: [],
};

export const fallbackCountryConfig: CountryConfig = {
  countries: fallbackBootstrap.countries.map((country, index) => ({
    ...country,
    country_type: country.code === "EP" ? "区域局" : "单一国家",
    display_order: index + 1,
    international_region: country.code === "US" ? "North America" : country.code === "EP" ? "Europe" : "Asia",
    business_region: country.code === "US" ? ["NORTH_AMERICA", "APEC"] : country.code === "EP" ? ["EUROPE"] : ["NORTHEAST_ASIA_JP_KR", "APEC"],
    region_remark: "第一期演示数据，用于报价工作台联动。",
  })),
  treaty_rules: [
    {
      id: "treaty-us-pct",
      country_code: "US",
      treaty_name: "PCT",
      membership_type: "成员国",
      enabled: true,
      effective_date: "1978-01-24",
      expiry_date: null,
      remark: "用于判断 PCT 进入路径可用性。",
    },
    {
      id: "treaty-ep-epc",
      country_code: "EP",
      treaty_name: "EPC",
      membership_type: "区域局",
      enabled: true,
      effective_date: "1977-10-07",
      expiry_date: null,
      remark: "用于欧洲阶段和生效路径判断。",
    },
  ],
  path_rules: [
    {
      id: "path-us-invention-pct",
      country_code: "US",
      application_type: "发明",
      filing_route: "PCT进入",
      route_detail: "有检索报告",
      affects_official_fee: true,
      affects_local_service_fee: true,
      affects_inhouse_service_fee: true,
      affects_questions: true,
      affects_documents: true,
      affects_deadlines: true,
      affects_translation: true,
      affects_display: true,
      enabled: true,
      effective_date: "2026-01-01",
      remark: "PCT 进入美国国家阶段。",
    },
    {
      id: "path-jp-invention-paris",
      country_code: "JP",
      application_type: "发明",
      filing_route: "巴黎公约",
      route_detail: "",
      affects_official_fee: true,
      affects_local_service_fee: true,
      affects_inhouse_service_fee: true,
      affects_questions: true,
      affects_documents: true,
      affects_deadlines: true,
      affects_translation: true,
      affects_display: true,
      enabled: true,
      effective_date: "2026-01-01",
      remark: "日本巴黎公约路径。",
    },
  ],
  deadline_rules: [
    {
      id: "deadline-us-pct",
      country_code: "US",
      application_type: "发明",
      filing_route: "PCT进入",
      route_detail: "有检索报告",
      pct_chapter_one_deadline: "30 个月",
      has_substantive_exam: true,
      substantive_exam_mode: "无需单独请求",
      accepts_substantive_exam: true,
      has_early_publication: false,
      application_cycle: "2-4 年",
      protection_term: "自申请日起 20 年",
      enabled: true,
      effective_date: "2026-01-01",
      remark: "复杂期限例外进入非常规事项或知识库。",
    },
    {
      id: "deadline-jp-paris",
      country_code: "JP",
      application_type: "发明",
      filing_route: "巴黎公约",
      route_detail: "",
      pct_chapter_one_deadline: "",
      has_substantive_exam: true,
      substantive_exam_mode: "需单独提出",
      accepts_substantive_exam: true,
      has_early_publication: true,
      application_cycle: "2-5 年",
      protection_term: "自申请日起 20 年",
      enabled: true,
      effective_date: "2026-01-01",
      remark: "实审请求期限后续可细化为独立期限项。",
    },
  ],
  entity_type_rules: [
    {
      id: "entity-us-invention",
      country_code: "US",
      application_type: "发明",
      filing_route: "PCT进入",
      enabled: true,
      entity_types: ["大实体", "小实体", "微实体"],
      affects_official_fee: true,
      affects_questions: true,
      requires_customer_confirmation: true,
      requires_supporting_documents: true,
      remark: "实体类型影响美国官费。",
    },
  ],
  language_rules: [
    {
      id: "language-jp-cn-ja",
      country_code: "JP",
      application_type: "发明",
      accepted_languages: ["日文"],
      source_language: "中文",
      target_language: "日文",
      intermediate_language: "",
      needs_second_translation: false,
      recommended_scheme_id: "cn-ja-china-translator",
      default_translation_fee: true,
      allow_scheme_switch: true,
      enabled: true,
      remark: "报价台默认带出中译日。",
    },
    {
      id: "language-us-cn-en",
      country_code: "US",
      application_type: "发明",
      accepted_languages: ["英文"],
      source_language: "中文",
      target_language: "英文",
      intermediate_language: "",
      needs_second_translation: false,
      recommended_scheme_id: "cn-en-standard",
      default_translation_fee: true,
      allow_scheme_switch: true,
      enabled: true,
      remark: "客户已有英文稿时可切换为无需翻译。",
    },
  ],
  fx_tax_rules: [
    {
      id: "fx-us-usd-cny",
      country_code: "US",
      official_currency: "USD",
      official_quote_currency: "USD",
      local_service_currency: "USD",
      local_service_currency_options: ["USD", "CNY"],
      quote_currency: "USD",
      fx_rate: "1",
      tax_rate: "0",
      tax_included: false,
      lock_on_formal_quote: true,
      version: "FX-2026-06-06",
      enabled: true,
      remark: "正式报价生成时锁定。",
    },
    {
      id: "fx-jp-jpy-cny",
      country_code: "JP",
      official_currency: "JPY",
      official_quote_currency: "JPY",
      local_service_currency: "JPY",
      local_service_currency_options: ["JPY", "CNY"],
      quote_currency: "JPY",
      fx_rate: "1",
      tax_rate: "10",
      tax_included: false,
      lock_on_formal_quote: true,
      version: "FX-2026-06-06",
      enabled: true,
      remark: "税率按费用类型进一步判断。",
    },
  ],
  special_rules: [
    {
      id: "special-us-bypass",
      country_code: "US",
      application_type: "发明",
      filing_route: "PCT进入",
      rule_type: "BYPASS",
      enabled: true,
      triggers_extra_fee: true,
      triggers_risk_warning: true,
      requires_customer_confirmation: true,
      risk_summary: "选择 BYPASS 路径时需确认文件和费用差异。",
      linked_rule_code: "US-BYPASS",
      remark: "特殊路径由报价问题触发。",
    },
  ],
};

export const initialForm: QuotationForm = {
  client_name: "智造未来科技有限公司",
  client_contact: "Lina",
  consultant_email: "suri@example.com",
  country_code: "US",
  country_codes: ["US"],
  application_type: "发明",
  filing_route: "PCT进入",
  pct_route_detail: "",
  entity_type: "",
  currency: "USD",
  has_case: true,
  case_title: "一种高效热管理结构",
  applicant_count: 1,
  priority_count: 1,
  claim_count: 18,
  description_pages: 36,
  drawing_pages: 6,
  needs_translation: true,
  translation_quantity_one: 1200,
  translation_quantity_two: 3,
  remark: "",
  status: "已生成报价",
};

export const importantNotes = [
  "本报价基于正常新申请程序。",
  "非常规事项如客户另有需求，将另行报价确认。",
  "审查、授权及年费阶段费用为后续预估，实际发生时另行确认。",
];
